### ISSUE TITLE
Error: Cannot find module /app/user/dist/src/index.js

### ISSUE THREAD

**Issue by shenhonglei** [anttiviljami/sftp-upload-http-api#3]
Error: Cannot find module '/app/user/dist/src/index.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sftp-upload-http-api@1.0.0 start: `node --max_old_space_size=500 dist/src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sftp-upload-http-api@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-13T04_24_49_785Z-debug.log

**Comment by anttiviljami** [comment]
Looks like you haven't built the software with `tsc`
